import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from 'next-auth'
import SessionProvider from "./components/SessionProvider"

import NavMenu from './components/NavMenu'
import { redirect } from 'next/navigation'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="bg-blue-500">
            <main className="mx-auto max-w-5xl h-screen">
              {children}
            </main>
          </div>
        </SessionProvider>
      </body>
    </html>
  )
}
